dtbo-y = sm8150-sdx50m-mtp-$(CONFIG_ZTE_BOARD_NAME)-overlay.dtbo
dtbo-y += sm8150-mtp-$(CONFIG_ZTE_BOARD_NAME)-overlay.dtbo
sm8150-sdx50m-mtp-$(CONFIG_ZTE_BOARD_NAME)-overlay.dtbo-base := sm8150-v2-$(CONFIG_ZTE_BOARD_NAME).dtb
sm8150-mtp-$(CONFIG_ZTE_BOARD_NAME)-overlay.dtbo-base := sm8150-v2-$(CONFIG_ZTE_BOARD_NAME).dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
