dtbo-y = sm8150-sdx50m-mtp-pine-overlay.dtbo
dtbo-y += sm8150-mtp-pine-overlay.dtbo
sm8150-sdx50m-mtp-pine-overlay.dtbo-base := sm8150-v2-pine.dtb
sm8150-mtp-pine-overlay.dtbo-base := sm8150-v2-pine.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
