ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_utils
ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_cpas/include
ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_sensor_module/cam_sensor_utils
ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_sensor_module/cam_sensor_io
ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_sensor_module/cam_cci
ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_sensor_module/cam_sensor
ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_smmu
ccflags-y += -Iinclude/linux

obj-$(CONFIG_SPECTRA_CAMERA)   += zte_camera_sensor_util.o


