ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_utils
ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_core
ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_sync
ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_smmu
ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_cdm
ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_lrme
ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_lrme/lrme_hw_mgr
ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_lrme/lrme_hw_mgr/lrme_hw
ccflags-y += -Idrivers/media/platform/msm/zte_camera
ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_cpas/include

obj-$(CONFIG_SPECTRA_CAMERA) += lrme_hw/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_lrme_hw_mgr.o
