ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_core
ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_cpas/include
ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_sensor_module/cam_cci
ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_sensor_module/cam_sensor_io
ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_sensor_module/cam_sensor_utils
ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_smmu/
ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_utils

ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_sensor_module/zte_io
ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_sensor_module/zte_cam_eeprom
obj-$(CONFIG_SPECTRA_CAMERA) += cam_sensor_dev.o cam_sensor_core.o cam_sensor_soc.o
