snd-soc-tfa98xx-objs := tfa98xx.o
snd-soc-tfa98xx-objs += tfa_container.o
snd-soc-tfa98xx-objs += tfa_dsp.o
snd-soc-tfa98xx-objs += tfa_init.o

obj-$(CONFIG_ZTE_FEATURE_NXP9894_SMART_PA)	+= snd-soc-tfa98xx.o
