ccflags-y += -Idrivers/media/platform/msm/zte_camera
ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_hyp_intf
ccflags-y += -Idrivers/media/platform/msm/zte_camera/cam_utils
obj-$(CONFIG_SPECTRA_CAMERA) += cam_hyp_intf.o
